### ISSUE TITLE
support silent mode

### ISSUE THREAD

**Issue by mkh48v** [omnis-labs-company/omnis#235]
like verbose=0

i think we can control verbose level on application.py

also, we can erase unnecessary printing codes

**Comment by mkh48v** [comment]
also check cuda and tensorflow log level

**Comment by 2013-11390** [comment]
https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information
We can remove tensorflow log by using os.environ. But I don't know it's proper to use this option in omnis application level.
We can remove deep block site log by using use_deepblock_site_log = false option in application level
