### ISSUE TITLE
implement custom flow_from_directory

### ISSUE THREAD

**Issue by mkh48v** [omnis-labs-company/omnis#283]
keras' flow_from_directory raises an error when input class changes after first training.

i suspect that it checks model's output_shape and always raises an error because input class directory and the output_shape is not the same

check keras' flow_from_directory and implement more flexible algorithm

**Comment by 2013-11390** [comment]
we use flow_from_directory in train function, but class_indices in model is decided in prepare_train_data function. 
It is impossible to fix this issue unless we recreate the model in train function.

**Comment by 2013-11390** [comment]
If we want to change classes after first training. We should recreate model with new classes. In this case, I we can load weights with skipping some layers. I think it is not related to flow_from_directory.
