### ISSUE TITLE
refactor codes

### ISSUE THREAD

**Issue by mkh48v** [omnis-labs-company/omnis#320]
maybe we can use

https://app.codacy.com/project/mkh48v/omnis/dashboard

**Comment by ik1ne** [comment]
Will write wiki page for coding rules.

**Comment by ik1ne** [comment]
Besides that, Pull Request #347 about lib folder refactoring has been opened.

**Comment by ik1ne** [comment]
#347 merged raising our Codacity quality from C to B.
However, we still need to fix more sensitive whitespace issues and some naming issues.

**Comment by 2013-11390** [comment]
I think this issue couldn't be closed, I'd like to ask @ik1ne . Why don't we close this issue and make code refactoring issue more specific. Such as Refactoring some application or Using pylint for code reactoring.

**Comment by ik1ne** [comment]
@2013-11390 good point, this issue will be closed and if required another refactor issue will be opened with proper title.
