### ISSUE TITLE
Add super resolution app

### ISSUE THREAD

**Issue by 2013-11390** [omnis-labs-company/omnis#323]
Search SRGAN

**Comment by mkh48v** [comment]
check
https://github.com/krasserm/super-resolution

**Comment by 2013-11390** [comment]
If we predict 1280 * 720 image in super resolutioin app, it takes about 40G of RAM. We should limit the image size or removing patch method for super resolution

**Comment by 2013-11390** [comment]
Since Super resolution app does not perform well so we close this issue temporally
