### ISSUE TITLE
add another image segmentation model

### ISSUE THREAD

**Issue by mkh48v** [omnis-labs-company/omnis#340]
check

http://cs231n.stanford.edu/slides/2018/cs231n_2018_ds06.pdf

**Comment by 2013-11390** [comment]
As you can see from above slides. Mask RCNN is modern and better version of RCNN and faster RCNN. So I think it's not important to add other segmentation models such as RCNN and Faster RCNN. Also I add UNet Segmentation in Science category. So I'll close this issue.
