### ISSUE TITLE
Source Control issues(Direct push to master, PR merge policy)

### ISSUE THREAD

**Issue by ik1ne** [omnis-labs-company/omnis#368]
Currently it is allowed to push to master directly.
However, we now have Codacy automatic PR review so I think it is better to prevent master direct push and force all code changes to be reviewed by Codacy.
Also, I think we should add merge policy requiring Admin reviews.
Any opinion about this, @mkh48v , @2013-11390 , @12rics ?

**Comment by mkh48v** [comment]
agree

**Comment by 2013-11390** [comment]
agree

**Comment by ik1ne** [comment]
Done.
